name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com
      - run: npm --version
      - run: npm ci
      - run: npm login --registry=https://npm.pkg.github.com/ --scope=@dealcraft
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --registry=https://npm.pkg.github.com/ --scope=@dealcraft
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm logout --scope=dealcraft --registry=https://npm.pkg.github.com/
